version: '3.3'

services:
  myapp:
    image: clamaud/compta:1.1
    ports:
    - '8082:8080' 
  mysql:
    image: mysql:8.0.16
    restart: always
    environment:
    - MYSQL_USER=clamaud
    - MYSQL_PASSWORD=voltaire
    - MYSQL_ROOT_PASSWORD=example
    - MYSQL_DATABASE=compta
    ports:
    - '3308:3306'
    volumes:
    - mysql-compta:/var/lib/mysql
    - ../db-dump:/docker-entrypoint-initdb.d
  
  jenkins:
    image: jenkins/jenkins:lts
    ports: [ "8280:8080" ]
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
    - jenkins:/var/jenkins_home
   
  nexus:
    image: sonatype/nexus3
    ports: [ "8281:8081" ]
    volumes:
    - nexus-data:/nexus-data

volumes:
  mysql-compta:
  jenkins:
  nexus-data:


