version: '3.3'

services:
  myapp:
    build:
      context: .
    image: compta:1.0
    container_name: compta
    ports:
    - '8080:8080' 
  mysql:
    image: mysql:8.0.16
    restart: always
    environment:
    - MYSQL_USER=clamaud
    - MYSQL_PASSWORD=voltaire
    - MYSQL_ROOT_PASSWORD=example
    - MYSQL_DATABASE=compta
    ports:
    - '3308:3306'
    volumes:
    - mysql-compta:/var/lib/mysql
    - ../db-dump:/docker-entrypoint-initdb.d

volumes:
  mysql-compta:


